# WARNING: This file is autogenerated by the deploy script. Any changes will be overridden
{
  url = "file:///data/local/tmp/n-o-d/bootstrap-aarch64.zip";
  hash = "sha256-fZyqldmHWbv2e6543mwb5UPcKxcODRg+PDvZNcjVyUU=";
}
