# WARNING: This file is autogenerated by the deploy script. Any changes will be overridden
{
  url = "https://nix-on-droid.unboiled.info/bootstrap-testing/bootstrap-aarch64.zip";
  hash = "sha256-fZyqldmHWbv2e6543mwb5UPcKxcODRg+PDvZNcjVyUU=";
}
