# WARNING: This file is autogenerated by the deploy script. Any changes will be overridden
{
  url = "file:///data/local/tmp/n-o-d/bootstrap-x86_64.zip";
  hash = "sha256-1WZBmFNEmZucOwuzDAFO+Sl+b2XO7Lp1aQr/4egl4wU=";
}
